#+title: Arnes Dotfiles
#+author: Arne Magnus Tveita Løken
#+options: toc:2

* Innholdsfortegnelse :toc:
- [[#hva-er-dette][Hva er dette?]]
- [[#lisensiering][Lisensiering]]

* Hva er dette?
Dotfiler er konfigurasjonsfiler som brukes til å personliggjøre Linux- og Unixbaserte systemer. Navnet `dotfiler' kommer av at filnavnet begynner med et punktum -- en dot. Punktumet først i fil- eller katalognavnet indikerer at det er en gjemt fil eller ei gjemt mappe. Dette repoet inneholder mine personlige dotfiler. De lagres her av bekvemmelighetsårsaker slik at jeg enkelt kan få tilgang til dem på nye maskiner eller nye installasjoner. Eventuelt kan også andre potensielt hente inspirasjon fra dem til sin egen konfigurasjon.

* Lisensiering
Filene i dette repoet er lisensiert under MIT-lisensen, som er en svært liberal lisens. Denne muliggjør bruk, kopiering, distribusjon, salg, med videre, av programvaren. Med andre ord, gjør med den hva du selv ønsker. Det eneste kravet MIT-lisensen påtrykker er at lisensen og oppahvsrettsnotisen tilgjengeliggjøres sammen med programvaren.
