;; Tangle org file if needed
(let* ((default-directory user-emacs-directory)
       (org-file "configuration.org")
       (el-file "configuration.el")
       (changed-at (file-attribute-modification-time (file-attributes org-file))))
  (require 'org-macs)
  (unless (org-file-newer-than-p el-file changed-at)
    (require 'ob-tangle)
    (org-babel-tangle-file org-file el-file "emacs-lisp"))
  (load-file el-file))
