name: Export README.org to GFM

on:
  push:
    paths:
      - README.org
      - .ci/banner.md
  workflow_dispatch:

jobs:
  export-readme:
    name: Org to GFM
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Emacs and Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y emacs-nox pandoc
    
    - name: Export README.org to GFM using Emacs and Pandoc
      run: |
        emacs --batch README.org \
              --eval "(require 'package)" \
              --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" \
              --eval "(package-initialize)" \
              --eval "(unless (package-installed-p 'ox-pandoc) (package-refresh-contents) (package-install 'ox-pandoc))" \
              --eval "(require 'ox-pandoc)" \
              --eval "(setq org-pandoc-options '((standalone . t)))" \
              --eval "(org-pandoc-export-to-file 'gfm \"README.gfm.md\")"

    - name: Prepend header banner to README.md
      run: |
        cat .ci/banner.md README.gfm.md > README.md
    
    - name: Clean up temporary file
      run: rm README.gfm.md

    - name: Import PGP key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

    - name: Configure Git + GPG sign
      run: |
        KEYID=$(gpg --list-secret-keys --with-colons | grep '^sec' | cut -d: -f5)
        git config user.name "GitHub Actions Bot"
        git config user.email "117858954+amtloken@users.noreply.github.com"
        git config user.signingkey "$KEYID"
        git config commit.gpgsign true

    - name: Commit and push updated README.md
      run: |
        git add README.md
        git diff --cached --quiet || git commit -m "Auto-export README.md from README.org"
        git push
      

