name: Export README.org to GFM

on:
  push:
    paths:
      - README.org
      - .ci/banner.md
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export-readme:
    name: Org to GFM
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        # Fetch full history for proper Git operations
        fetch-depth: 0

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
    
    - name: Export README.org to GFM using Pandoc
      run: |
        pandoc <(awk '/^\*+ .*:toc:/{flag=1; level=gsub(/\*/, "&"); next} /^\*+/ && flag{new_level=gsub(/\*/, "&"); if(new_level<=level){flag=0}} !flag' README.org) \
          -f org -t gfm --standalone --toc --toc-depth=2 -o README.gfm.md

    - name: Prepend header banner to README.md
      run: |
        cat .ci/banner.md README.gfm.md > README.md
    
    - name: Clean up temporary file
      run: rm README.gfm.md

    - name: Import PGP key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

    - name: Configure Git + GPG sign
      run: |
        KEYID=$(gpg --list-secret-keys --with-colons | grep '^sec' | cut -d: -f5)
        git config user.name "GitHub Actions Bot"
        git config user.email "117858954+amtloken@users.noreply.github.com"
        git config user.signingkey "$KEYID"
        git config commit.gpgsign true

    - name: Commit and push updated README.md
      run: |
        git add README.md
        if ! git diff --cached --quiet; then
          git commit -m "Auto-export README.md from README.org [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
      

